### ISSUE TITLE
[bug] remediation-resource-id-parameter is a pointless flag

### ISSUE THREAD

**Issue by jack1902** [awslabs/aws-config-rdk#226]
### Description

The flag `--remediation-resource-id-parameter` is pointless. It literally does nothing. I assume it was originally intended for the cloudformation to generate things such as:

### Steps to reproduce

```yml
      Parameters:
        AutomationAssumeRole:
          StaticValue:
            Values:
              - "ARN"
        S3BucketName:
          ResourceValue:
            Value: RESOURCE_ID
```

I believe the intended use was to be placed under `ResourceValue` for the Param `S3BucketName`? in the example above?

If i pass:
```sh
rdk modify public_buckets \
  --auto-remediate \
  --auto-remediation-retry-attempts 5 \
  --auto-remediation-retry-time 60 \
  --remediation-action PublicBucketsConfigRuleSSMDocument \
  --remediation-parameters '{"AutomationAssumeRole":{"StaticValue":{"Values":["ROLEARN"]}},"S3BucketName":{"ResourceValue":{"Value":"RESOURCE_ID"}}}'
```

Then this creates valid Cloudformation

## Desired Change

That the redundant flag is removed from the `RDK` or serves its actual purpose
